version: '3'
services:
  lb:
    image: "nginx_cus:v1"
    networks:
      - vnet
    deploy:
      replicas: 5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/
  web:
    image: "docker_web:v4"
    deploy:
      replicas: 3
    networks:
      - vnet
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    deploy:
      replicas: 2
    networks:
      - vnet
    volumes:
      - ./redis/data:/data
networks:
  vnet:

